college = ['student', 'teacher','gaurd', 'peoun']
print(type(college))
print(college)
print(college[0].title())
print(college[1].upper())
print('There is many '+college[0].title()+' in my college')
college[0]='number of students'
print(college) 
college.append('akash')
print(college)
college.insert(2,'sahu')
print(college)
del college[2]
print(college)
print(college.pop())
print(college.pop())
print(college.pop())
print(college)
print('My college has '+college.pop(0).title())
print(college)
college.append('akash')
college.append('sahu')
college.append('python')
college.append('java')
print(college)
college.remove('sahu')
print(college)
program = 'python'
college.remove(program)
print('A '+program.title()+" is easyer than java")
print(college)
college.sort()
print(college)
college.sort(reverse=True)
print(college)
college.append('sahu')
print(sorted(college))
print(college)
print("The length of the list is : "+str(len(college)))
print("The length of the list is : ",len(college))